package message

import maybe "github.com/seoester/adcl/protocol/maybe"

// Code generated by adcl/protocol/generator. DO NOT EDIT.

type RESFlag string

const (
	RESFlagFN RESFlag = "FN"
	RESFlagSI         = "SI"
	RESFlagSL         = "SL"
	RESFlagTO         = "TO"
	RESFlagTR         = "TR"
	RESFlagTD         = "TD"
)

var _ ParamAccessor = &RESContent{}

type RESContent struct {
	FN    string
	fnStr string

	SI    int
	siStr string

	SL    maybe.Int
	slStr string

	TO    string
	toStr string

	TR    maybe.Base32Value
	trStr string

	TD    maybe.Int
	tdStr string

	Flags map[string]string

	// FI, FO, DA; EXT § 3.27 ASCH - Extended searching capability (EXT v1.0.8)
}

func (r *RESContent) Positional() []string {
	return []string{}
}

func (r *RESContent) PosLen() int {
	return 0
}

func (r *RESContent) PosAt(i int) string { return "" }

func (r *RESContent) Named() map[string]string { return make(map[string]string) }

func (r *RESContent) NamedGet(key string) (string, bool) { return "", false }
