// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package maybe

import "net"

type IP struct {
	Value net.IP
	IsSet bool
}

func (m *IP) Get() (net.IP, bool) {
	return m.Value, m.IsSet
}

func (m *IP) GetDefault(def net.IP) net.IP {
	if m.IsSet {
		return m.Value
	} else {
		return def
	}
}

func (m *IP) Set(val net.IP) {
	m.Value = val
	m.IsSet = true
}

func (m *IP) Unset() {
	m.IsSet = false
}
