// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package maybe

import (
	"github.com/seoester/adcl/protocol/encoding"
)

type Base32Value struct {
	Value *encoding.Base32Value
	IsSet bool
}

func (m *Base32Value) Get() (*encoding.Base32Value, bool) {
	return m.Value, m.IsSet
}

func (m *Base32Value) GetDefault(def *encoding.Base32Value) *encoding.Base32Value {
	if m.IsSet {
		return m.Value
	} else {
		return def
	}
}

func (m *Base32Value) Set(val *encoding.Base32Value) {
	m.Value = val
	m.IsSet = true
}

func (m *Base32Value) Unset() {
	m.IsSet = false
}
